cmf_sonata_phpcr_admin_integration:
    bundles:
        content: ~
        
cmf_content:
    persistence:
        phpcr:
            content_basepath: /cms/content
            enabled:          true
#            admin_class:      ~
#            document_class:   ~

#            use_sonata_admin: auto        
cmf_resource:
    repositories:
        default:
            type: doctrine/phpcr-odm
            basepath: ~