doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
            # connection: default

            # requires DoctrineCacheBundle
            # caches:
            #     meta: doctrine_cache.providers.phpcr_meta
            #     nodes: doctrine_cache.providers.phpcr_nodes
            # enable logging
            logging: true
            # enable profiling in the debug toolbar.
            profiling: true
        workspace: default
        username: admin
        password: admin
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: "%kernel.debug%"
