# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
imports:
    - { resource: ../../src/AppBundle/Resources/config/services.yml }
parameters:
    #parameter_name: value
           