sonata_doctrine_phpcr_admin:
    templates:
        form:
            # Default:
            - SonataDoctrinePHPCRAdminBundle:Form:form_admin_fields.html.twig
        filter:
            # Default:
            - SonataDoctrinePHPCRAdminBundle:Form:filter_admin_fields.html.twig
        types:
            list:
                # Prototype
#                name:                 []
            show:
                # Prototype
#                name:                 []
        pager_results:        SonataDoctrinePHPCRAdminBundle:Pager:simple_pager_results.html.twig

    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        AppBundle\Document\Page:
            valid_children:
                - AppBundle\Document\Post
        AppBundle\Document\Post:
            valid_children: []        
        Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ActionBlock
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock:
            valid_children: []
        # See :doc:`document_tree`.
        class:
            # class names of valid children, manage tree operations for them and hide other children
            valid_children:       []
            image:        
        AppBundle\Document\Site:
            valid_children:
                - all        
    document_tree_defaults:  [locale]
    document_tree_options:
        # Depth to which to fetch tree children when rendering the initial tree
        depth:                1
        # Exact check if document has children. For large trees, set to false for better performance, but user might needs to click on expand to see there are no children.
        precise_children:     true
        # Whether moving a node in the tree asks for confirmation.
        confirm_move:         true
